[package]
name = "vote"
version = "0.1.0"
authors = ["Curtis Smith <Curtis.MBSmith@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sequoia-openpgp = "0.3"
